client/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("create/", views.create_client, name="create_client"),
    path("location_reservation/", views.location_reservation, name="location_reservation"),
    path("location_reservation/louer/", views.create_location, name="louer"),
    path("location_reservation/create_zone/", views.create_zone, name="create_zone"),
    path("location_reservation/reserver/", views.create_reservation, name="create_reservation"),
    path("location_reservation/locations/", views.get_locations, name="get_locations"),
    path("location_reservation/reservations/", views.get_reservations, name="get_reservations"),
    path("gestion_piscine/", views.gestion_piscine, name="gestion_piscine"),
    path("gestion_piscine/pool_entry/", views.pool_entry, name="pool_entry"),
    path("gestion_piscine/pool_records_per_date/", views.pool_records_per_date, name="pool_records_per_date"),
]

marbika/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from employe.views import dashmin, login_user, logout_user

urlpatterns = [
    path("", dashmin, name="dashmin"),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
    path('admin/', admin.site.urls),
    path("employe/", include("employe.urls")),
    path("salon/", include("salon.urls")),
    path("restaurant/", include("restaurant.urls")),
    path("client/", include("client.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

salon/urls.py
from django.urls import path

from salon.views import *

urlpatterns = [
    path("services/", services, name="services"),
    path("services/add/", add_service, name="add_service"),
    path("services/get_services/", get_services, name="get_services"),
    path("services/get/", get_service, name="get_service"),
    path("services/update/", update_service, name="update_service"),
    path("services/montant_par_service/", montant_genere_par_service, name="montant_par_service"),
    path("categorie/add/", add_category, name="add_categorie"),
    path("categorie/get_categories/", get_categories, name="get_categories"),
    path("prix/", prix_services, name="prix_services"),
    path("prix/add/", add_prix_service, name="add_prix_services"),
    path("prestations/", prestations, name="prestations"),
    path("get_prestations/", get_prestations, name="get_prestations"),
    path("prestations_en_attentes/", prestations_en_attentes, name="prestations_en_attentes"),
    path("prestations/add/", add_prestation, name="add_prestations"),
    path("prestations/confirmer_prestation/", confirmer_prestation, name="confirmer_prestation"),
    path("prestations/details/<str:id_prestation>", get_prestation_details, name="get_prestation_details"),
    path("prestations/<str:service_id>/", get_prix_service, name="get_prix_service"),
    path("produits/", produits, name="produits"),
    path("produits/add/", add_produit, name="add_produit"),
    path("produits/list/", get_produits, name="get_produits"),
    path("produits/appro/", approvisionner_produit, name="approvisionner"),
    path("produits/shop/", shop_produits, name="shop"),
    path("produits/shop/details/<str:id_vente>/", details_vente, name="shop"),
    path("produits/vente/", vente_produits, name="vente_produits"),
    path("produits/list_clients/", get_clients, name="list_clients"),
    path("produits/liste_ventes/", get_ventes, name="liste_ventes"),
    path("depenses/", depenses, name="depenses"),
    path("depenses/add/", creer_depense, name="creer_depense"),
    path("depenses/list/", get_depenses, name="get_depenses"),
    path("depenses/calcul_depenses/", depense_semaine_mois_annee, name="calcul_depenses"),
]

client/models.py
from django.db import models, transaction
from django.db.models import Max

from employe.models import MyBaseModel


class Client(MyBaseModel):
    sexes = [(1, "Homme"), (2, "Femme")]

    code_client = models.CharField(
        max_length=7,
        unique=True,
        null=True,
        blank=True,
    )

    nom_complet = models.CharField(max_length=200, null=True, blank=True)
    telephone = models.CharField(max_length=20, null=True, blank=True)
    sexe = models.SmallIntegerField(choices=sexes, null=True)


    def save(self, *args, **kwargs):
        if not self.code_client:
            self.code_client = self.generate_code_client()
        super().save(*args, **kwargs)


    def __str__(self):
        return f'{self.code_client} - {self.nom_complet} - {self.telephone}'


    @staticmethod
    def generate_code_client():
        with transaction.atomic():
            last_code = (
                Client.objects.select_for_update()
                .aggregate(max_code=Max("code_client"))["max_code"]
            )

            if last_code:
                last_number = int(last_code[1:])
            else:
                last_number = 0

            return f"C{last_number + 1:04d}"


class ZoneAReserver(MyBaseModel):
    STATUT_CHOICES = [('libre', "LIBRE"), ('reserve', "RESERVEE")]

    nom = models.CharField(max_length=100)
    statut = models.CharField(max_length=20, choices=STATUT_CHOICES, default='libre')

    def __str__(self):
        return f"Zone: {self.nom} - {self.get_statut_display()}"

class Reservation(MyBaseModel):
    TYPE = [(1, "Service"), (2, "Evénement")]
    ETAT_RESERVATION = [(1, "En cours"), (2, "Terminée"), (3, "Annulée"), (4, "En attente"), (5, "Confirmée")]

    type = models.SmallIntegerField(choices=TYPE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    zone = models.ForeignKey(ZoneAReserver, on_delete=models.CASCADE)
    etat_reservation = models.SmallIntegerField(choices=ETAT_RESERVATION)
    date_debut = models.DateField()
    date_fin = models.DateField()
    commentaire = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.zone.nom}"


class Location(MyBaseModel):
    STATUT_LOCATION = [
        ('en_attente', 'En attente'),
        ('confirmee', 'Confirmée'),
        ('en_cours', 'En cours'),
        ('terminee', 'Terminée'),
        ('annulee', 'Annulée'),
        ('expiree', 'Expirée'),
    ]
    TYPE = [(1, "Service"), (2, "Evénement")]

    locateur = models.ForeignKey(Client, on_delete=models.CASCADE)
    objet = models.CharField(max_length=120, null=True)
    zone = models.ForeignKey(ZoneAReserver, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)
    montant_a_payer = models.BigIntegerField()
    montant_reduit = models.BigIntegerField(null=True)
    date_debut = models.DateField()
    date_fin = models.DateField()
    statut = models.CharField(max_length=20, choices=STATUT_LOCATION, default='en_attente')
    type_location = models.SmallIntegerField(choices=TYPE)

    def __str__(self):
        return f"{self.zone.nom} - {self.locateur.nom_complet} - Début: {self.date_debut}, Fin: {self.date_fin}"


class Piscine(MyBaseModel):
    nb_client = models.IntegerField()
    prix_unitaire = models.BigIntegerField()
    reduction = models.BigIntegerField(null=True, default=0)
    note = models.CharField(max_length=255, null=True, blank=True)


class AbonnementGym(MyBaseModel):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    date_debut = models.DateTimeField()
    date_fin = models.DateTimeField(null=True, blank=True)
    is_active = models.BooleanField(default=True)


class SeanceGym(MyBaseModel):
    client = models.ForeignKey(Client, on_delete=models.SET_NULL, null=True)
    date_seance = models.DateTimeField(auto_now_add=True)

client/views.py
import http
import json
from datetime import datetime, timedelta

from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.utils.html import escape

from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from django.utils import timezone

from client.models import Client, ZoneAReserver, Location, Reservation, Piscine
from . import forms
from .forms import ZoneForm, LocationForm, ReservationForm, PiscineForm
from salon.views import currency

tmp_base = "client/"

def telephone_exists(telephone):
    # Check if Telephone already Exists
    phone = telephone.replace(" ", "")  # Supprimer les espaces dans le numéro
    try:
        client_found = Client.objects.get(telephone=phone)  # Recherche dans la DB
        return True
    except Client.DoesNotExist:
        return False


@login_required(login_url="login")
@require_http_methods(["POST"])
def create_client(request):
    try:
        data = json.loads(request.body)
        client = data.get('client')

        required_fields = ['sexe', 'fullname']
        for field in required_fields:
            if not escape(client.get(field)):
                return JsonResponse({"error": True, "msg": f"Le champ '{field}' est obligatoire."}, status=400)

        fullname = escape(client.get('fullname'))
        telephone = escape(client.get('telephone'))
        sexe = escape(client.get('sexe'))
        if telephone and telephone_exists(telephone):
            return JsonResponse({"error": True, "msg": "Ce Numéro existe déjà dans la Base de Données."}, status=400)

        user = request.user
        Client.objects.create(
            nom_complet=fullname, telephone=telephone, sexe=int(sexe), created_by=user
        )

        return JsonResponse({"success": True, "msg": "Nouveau Client créé avec succès !"}, status=200)

    except Exception as e:
        print(e)
        return JsonResponse({"error": True, "msg": "Une erreur est survenue lors de la création du Client, réessayer"}, status=400)


@login_required(login_url="login")
@require_http_methods(["GET"])
def location_reservation(request):
    context = {
        "page_title": "Location & Réservation",
        "form": forms.LocationForm(),
        "zone_form": ZoneForm(),
        "reservation_form": ReservationForm(),
    }
    return render(request, tmp_base + "location_reservation.html", context)


@login_required(login_url="login")
@require_http_methods(["POST"])
def create_zone(request):
    zone_form = ZoneForm(request.POST)
    if zone_form.is_valid():
        nom = zone_form.cleaned_data["nom"]
        statut = zone_form.cleaned_data["statut"]
        try:
            ZoneAReserver.objects.create(nom=nom, statut=statut, created_by=request.user)
            return JsonResponse({"success": True, "msg": "Zone crée avec succès !"})
        except Exception as e:
            print("Erreur :", e)
            return JsonResponse({"error": True, "msg": str(e)}, status=400)
    else:
        return JsonResponse({"error": True, "msg": "Données invalides"}, status=400)


@login_required(login_url="login")
@require_http_methods(["POST"])
def create_location(request):
    try:
        data = json.loads(request.body)

        id_client = escape(data.get("id_client"))
        id_zone = escape(data.get("id_zone"))

        if not check_zone_libre(id_zone):
            return JsonResponse({"error": True, "msg": "Cette Zone est déjà réservée."}, status=404)

        with transaction.atomic():

            current_client = Client.objects.get(id=id_client)
            current_zone = ZoneAReserver.objects.get(id=id_zone)

            Location.objects.create(
                locateur=current_client, zone=current_zone, description=escape(data.get("description")), montant_a_payer=escape(data.get("montant_a_payer")),
                montant_reduit=escape(data.get("remise")), date_debut=escape(data.get("date_debut")),
                date_fin=escape(data.get("date_fin")), statut=escape(data.get("statut")), type_location=escape(data.get("type_location")),
                created_by=request.user
            )

            current_zone.statut = 'reserve'
            current_zone.save()

        return JsonResponse({"success": True, "msg": f"Location enregistrée avec succès."})
    except Client.DoesNotExist:
        return JsonResponse({"error": True, "msg": "Le Client n'a été trouvé dans la Base de données"})
    except ZoneAReserver.DoesNotExist:
        return JsonResponse({"error": True, "msg": "La Zone à louer n'a été trouvé dans la Base de données"})
    except Exception as e:
        print("Erreur :", e)
        return JsonResponse({"error": True, "msg": str(e)})


# Verifier si la zone à reserver est 'libre' et renvoyer 'True'
def check_zone_libre(id_zone):
    try:
        ZoneAReserver.objects.get(id=id_zone, statut='libre')
        return True
    except ZoneAReserver.DoesNotExist:
        return False


@login_required(login_url="login")
@require_http_methods(["POST"])
def create_reservation(request):
    try:
        data = json.loads(request.body)

        id_client = escape(data.get("id_client"))
        id_zone = escape(data.get("id_zone"))

        if not check_zone_libre(id_zone):
            return JsonResponse({"error": True, "msg": "Cette Zone est déjà réservée."}, status=404)

        with transaction.atomic():

            reservation_reussie = False

            current_client = Client.objects.get(id=id_client)
            current_zone = ZoneAReserver.objects.get(id=id_zone)

            # Créer la Réservation
            new_reservation = Reservation.objects.create(
                type=escape(data.get("type")), client=current_client, zone=current_zone, etat_reservation=escape(data.get("statut")),
                date_debut=escape(data.get("date_debut")), date_fin=escape(data.get("date_fin")), commentaire=escape(data.get("commentaire")),
                created_by=request.user
            )

            # Mettre à jour la Zone réservée, mettre son statut sur "reserve"
            if new_reservation:
                current_zone.statut = 'reserve'
                current_zone.save()

                reservation_reussie = True

            if not reservation_reussie:
                raise Exception("Erreur inattendue")
        return JsonResponse({"success": True, "msg": "Réservation effectuée avec succès."})

    except Client.DoesNotExist:
        return JsonResponse({"error": True, "msg": "Le Client est introuvable."}, status=404)

    except ZoneAReserver.DoesNotExist:
        return JsonResponse({"error": True, "msg": "La zone à reserver est introuvable."}, status=404)

    except Exception as e:
        print("Erreur :", e)
        return JsonResponse({"error": True, "msg": str(e)})


@require_http_methods(["GET"])
def get_locations(request):
    try:
        list_locations: list = []

        locations = Location.objects.all()

        for location in locations:
            net_paye = location.montant_a_payer - location.montant_reduit
            list_locations.append({
                "id": location.id,
                "locateur": location.locateur.nom_complet,
                "telephone": location.locateur.telephone,
                "objet": location.objet,
                "zone": location.zone.nom,
                "description": location.description,
                "montant_a_payer": currency(location.montant_a_payer),
                "remise": currency(location.montant_reduit),
                "date_debut": location.date_debut.strftime("%d/%m/%Y"),
                "date_fin": location.date_fin.strftime("%d/%m/%Y"),
                "statut": location.get_statut_display(),
                "type_location": location.get_type_location_display(),
                "net_paye": f'<span class="text-success">{currency(net_paye)}</span>',
            })
        return JsonResponse({"success": True, "data": list_locations})
    except Location.DoesNotExist:
        return JsonResponse({"error": True, "msg": "Aucune Location enregistrée."}, status=404)


@require_http_methods(["GET"])
def get_reservations(request):
    try:
        reservations = Reservation.objects.all()

        list_reservations: list = []

        for reservation in reservations:
            list_reservations.append({
                "id": reservation.id,
                "type": reservation.get_type_display(),
                "client": reservation.client.nom_complet,
                "telephone": reservation.client.telephone,
                "zone": reservation.zone.nom,
                "etat_reservation": reservation.get_etat_reservation_display(),
                "date_debut": reservation.date_debut.strftime("%d/%m/%Y"),
                "date_fin": reservation.date_fin.strftime("%d/%m/%Y"),
                "commentaire": reservation.commentaire,
            })
        return JsonResponse({"success": True, "data": list_reservations}, status=200)
    except Reservation.DoesNotExist:
        return JsonResponse({"error": True, "msg": "Aucune reservation trouvée."}, status=404)

def gestion_piscine(request):
    context = {
        "page_title": "Gestion de la Piscine",
        "form": PiscineForm(),
    }
    return render(request, tmp_base + "gestion_piscine.html", context=context)


@login_required(login_url="login")
@require_http_methods(["POST"])
def pool_entry(request):
    try:
        data = json.loads(request.body)
        nb_client = data.get('nb_client')
        prix_unitaire = data.get('prix_unitaire')
        reduction = data.get('reduction')
        note = data.get('note')
        Piscine.objects.create(
            nb_client=nb_client, prix_unitaire=prix_unitaire,
            reduction=reduction, note=note, created_by=request.user
        )
        return JsonResponse({"success": True, "msg": "Enregistrement effectué avec succès."}, status=201)
    except json.decoder.JSONDecodeError:

client/templates/client/gestion_piscine.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block page_title %} {{ page_title }} {% endblock %}
{% block main %}
<!-- Row starts -->
<div class="row gx-4">
    <div class="col-sm-12">
        <div class="card mb-4">
            <form method="POST" action="{% url 'pool_entry' %}" id="poolEntry">
                <div class="card-header">
                    <h5 class="card-title">Gestion de la Piscine</h5>
                </div>
                <div class="card-body">

                    <!-- Row starts -->
                    <div class="row gx-4">
                        {% csrf_token %}

                        <div class="col-lg-3 col-sm-4 col-12">
                            <div class="mb-3">
                                <label for="id_nb_client" class="form-label">Nombre de clients</label>
                                {{ form.nb_client | as_crispy_field }}
                            </div>
                        </div>
                        <div class="col-lg-3 col-sm-4 col-12">
                            <div class="mb-3">
                                <label class="form-label" for="id_prix_unitaire">Prix Unitaire</label>
                                {{ form.prix_unitaire | as_crispy_field }}
                            </div>
                        </div>
                        <div class="col-lg-3 col-sm-4 col-12">
                            <div class="mb-3">
                                <label class="form-label" for="id_reduction">Remise</label>
                                {{ form.reduction | as_crispy_field }}
                            </div>
                        </div>
                        <div class="col-lg-3 col-sm-4 col-12">
                            <div class="mb-3">
                                <label class="form-label" for="id_note">Commentaire</label>
                                {{ form.note | as_crispy_field }}
                            </div>
                        </div>
                    </div>
                    <!-- Row ends -->

                </div>
                <div class="card-footer">
                    <div class="d-flex gap-2 justify-content-end">
                        <button type="submit" class="btn btn-primary me-4">
                            Valider
                        </button>
                        <button type="reset" class="btn btn-secondary" id="btnAnnuler">
                            Annuler
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <div class="d-flex flex-row flex-wrap mb-4 align-items-center card">
        <div class="col-sm-4 col-12">
            <!-- Card starts -->
            <div class="card mb-4">
                <div class="card-body">
                    <div class="m-0">
                        <label class="form-label" for="date_debut">Du</label>
                        <div class="input-group">
                            <span class="input-group-text">
                              <i class="bi bi-calendar4"></i>
                            </span>
                            <input type="text" id="date_debut" class="form-control datepicker"/>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Card ends -->
        </div>
        <div class="col-sm-4 col-12">
            <!-- Card starts -->
            <div class="card mb-4">
                <div class="card-body">
                    <div class="m-0">
                        <label class="form-label" for="date_fin">Au</label>
                        <div class="input-group">
                            <span class="input-group-text">
                              <i class="bi bi-calendar4"></i>
                            </span>
                            <input type="text" id="date_fin" class="form-control datepicker"/>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Card ends -->
        </div>
        <button type="button" class="btn btn-outline-primary" id="btnDateFilter">
            Appliquer
        </button>
    </div>
    <div class="col-sm-12">
        <div class="card mb-4">
            <div class="card-header">
                <h5 class="card-title">Piscine</h5>
            </div>
            <div class="card-body">
                <div class="table-outer">
                    <div class="table-responsive">
                        <table class="table table-striped truncate m-0" id="piscineTable">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Nombre de Personnes</th>
                                <th>Prix Unitaire</th>
                                <th>Total</th>
                                <th>Date</th>
                            </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Row ends -->

{% endblock main %}

{% block custom_js %}
<script src="{% static 'assets/js/datatables.min.js' %}"></script>
<script src="{% static 'assets/js/modernizr.js' %}"></script>
<script src="{% static 'assets/vendor/daterange/daterange.js' %}"></script>
<script src="{% static 'assets/vendor/daterange/custom-daterange.js' %}"></script>
<script>
    $(document).ready(function () {
        function getCSRFToken(){
            const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]');
            return csrfToken ? csrfToken.value : "";
        }

        var notyf = new Notyf();

        $("#poolEntry").submit(function(event){
            event.preventDefault();

            const actionUrl = $(this).attr('action');
            const formData = {
                nb_client: $("#id_nb_client").val().trim(),
                prix_unitaire: $("#id_prix_unitaire").val().trim(),
                reduction: $("#id_reduction").val().trim(),
                note: $("#id_note").val().trim()
            }
            console.log(formData);
            $.ajax({
                url: actionUrl,
                method: "POST",
                headers: { 'X-CSRFToken': getCSRFToken() },
                data: JSON.stringify(formData),
                contentType: 'application/json',
                dataType: 'json',
                success: function (res) {
                    loadPoolData(start, end)
                    notyf.success({
                      message: res.msg,
                      duration: 3000,
                      position: {
                        x: 'right',
                        y: 'top'
                      }
                    })
                    $("#btnAnnuler").trigger("click")
                },
                error: function (err) {
                    notyf.error({
                      message: res.msg,
                      duration: 3000,
                      position: {
                        x: 'right',
                        y: 'top'
                      }
                    })
                }
            })
        })

        var piscineTable = $("#piscineTable").DataTable({
            processing: true,
            searching: true,
            paging: true,
            info: false,
            columns: [
                {
                    data: null,
                    render: function(data, type, row, meta){
                        return meta.row + 1;
                      }
                },
                { data: 'nb_client' },
                { data: 'prix_unitaire' },
                { data: 'total' },
                { data: 'created_at' },
                { data: 'note' },
            ],
             columnDefs: [{
                "targets": 0,
                "searchable": false,
                "orderable": false
            }],
            order: [],
            rowCallback: function(row, data, index){
                $('td:eq(0)', row).html(index + 1)
            },
        });

        const myDate = new Date();
        const start = `${myDate.getFullYear()}-${myDate.getMonth() + 1}-${myDate.getDate()}`;
        const end = `${myDate.getFullYear()}-${myDate.getMonth() + 1}-${myDate.getDate()}`;

        loadPoolData(start, end)

        function loadPoolData(start, end){
            data = {dateDebut: start, dateFin: end};

            $.ajax({
                url: "/client/gestion_piscine/pool_records_per_date/",
                method: 'POST',
                headers: { 'X-CSRFToken': getCSRFToken() },
                data: JSON.stringify(data),
                contentType: 'application/json',
                dataType: 'json',
                success: function(res){
                    const data = res.data;
                    piscineTable.clear();
                    piscineTable.rows.add(data).draw();
                },
                error: function(err){
                    console.log(err);

                }
            })
        }

        // Appliquer le fitre de la Date
        $("#btnDateFilter").on('click', function(e){
            const date_debut_str = $("#date_debut").val()
            const date_fin_str = $("#date_fin").val()
            const date_debut = `${date_debut_str.split('/')[2]}-${date_debut_str.split('/')[1]}-${date_debut_str.split('/')[0]}`;
            const date_fin = `${date_fin_str.split('/')[2]}-${date_fin_str.split('/')[1]}-${date_fin_str.split('/')[0]}`;

            loadPoolData(date_debut, date_fin)

        })
    })
</script>

{% endblock %}