marbika/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from employe.views import dashmin, login_user, logout_user

urlpatterns = [
    path("", dashmin, name="dashmin"),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
    path('admin/', admin.site.urls),
    path("employe/", include("employe.urls")),
    path("salon/", include("salon.urls")),
    path("restaurant/", include("restaurant.urls")),
    path("client/", include("client.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

salon/urls.py
from django.urls import path

from salon.views import *

urlpatterns = [
    path("services/", services, name="services"),
    path("services/add/", add_service, name="add_service"),
    path("services/get_services/", get_services, name="get_services"),
    path("services/get/", get_service, name="get_service"),
    path("services/update/", update_service, name="update_service"),
    path("services/montant_par_service/", montant_genere_par_service, name="montant_par_service"),
    path("categorie/add/", add_category, name="add_categorie"),
    path("categorie/get_categories/", get_categories, name="get_categories"),
    path("prix/", prix_services, name="prix_services"),
    path("prix/add/", add_prix_service, name="add_prix_services"),
    path("prestations/", prestations, name="prestations"),
    path("get_prestations/", get_prestations, name="get_prestations"),
    path("prestations_en_attentes/", prestations_en_attentes, name="prestations_en_attentes"),
    path("prestations/add/", add_prestation, name="add_prestations"),
    path("prestations/confirmer_prestation/", confirmer_prestation, name="confirmer_prestation"),
    path("prestations/details/<str:id_prestation>", get_prestation_details, name="get_prestation_details"),
    path("prestations/<str:service_id>/", get_prix_service, name="get_prix_service"),
    path("produits/", produits, name="produits"),
    path("produits/add/", add_produit, name="add_produit"),
    path("produits/list/", get_produits, name="get_produits"),
    path("produits/appro/", approvisionner_produit, name="approvisionner"),
    path("produits/shop/", shop_produits, name="shop"),
    path("produits/shop/details/<str:id_vente>/", details_vente, name="shop"),
    path("produits/vente/", vente_produits, name="vente_produits"),
    path("produits/list_clients/", get_clients, name="list_clients"),
    path("produits/liste_ventes/", get_ventes, name="liste_ventes"),
    path("depenses/", depenses, name="depenses"),
    path("depenses/add/", creer_depense, name="creer_depense"),
    path("depenses/list/", get_depenses, name="get_depenses"),
    path("depenses/calcul_depenses/", depense_semaine_mois_annee, name="calcul_depenses"),
]

salon/models.py
import uuid
from django.db import models

from client.models import Client
from employe.models import MyBaseModel, Employe


class CategorieService(MyBaseModel):
    nom_categorie = models.CharField(max_length=120)

    def __str__(self):
        return self.nom_categorie


class Service(MyBaseModel):
    designation = models.CharField(max_length=120)
    categorie = models.ForeignKey(CategorieService, on_delete=models.CASCADE)
    prix_service = models.BigIntegerField(null=True)

    def __str__(self):
        return self.designation


class PrixService(MyBaseModel):
    prix_service = models.BigIntegerField()
    service = models.ForeignKey(Service, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.service.designation} - {self.prix_service}"


class InitPrestation(MyBaseModel):
    status = [("en_attente", "En attente"), ("confirmé", "Confirmé")]
    reference = models.CharField(max_length=20, unique=True, blank=True)
    montant_total = models.BigIntegerField()
    remise = models.BigIntegerField(default=0)
    client = models.ForeignKey(Client, null=True, on_delete=models.SET_NULL)
    statut = models.CharField(max_length=10, choices=status, default="en_attente")
    montant_attribue = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.reference} - {self.client} - Montant : {self.montant_total}"


class Prestation(MyBaseModel):
    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True)
    prix_service = models.BigIntegerField()
    init_prestation = models.ForeignKey(InitPrestation, on_delete=models.CASCADE)
    fait_par = models.ManyToManyField("employe.Employe", related_name="prestations_realisees")
    quantite = models.SmallIntegerField(default=1)

    def __str__(self):
        return f"{self.service.designation} - InitPrest: {self.init_prestation}"


class Produit(MyBaseModel):
    designation = models.CharField(max_length=120, null=True, blank=True)
    qr_code = models.CharField(max_length=255, null=True)
    stock = models.PositiveIntegerField(default=0)
    prix_achat = models.BigIntegerField(default=0, null=True, blank=True)
    prix_vente = models.BigIntegerField(default=0)
    image = models.ImageField(null=True, blank=True, upload_to="produits/")

    def __str__(self):
        return f"{self.designation} - PVU: {self.prix_vente} | Stock {self.stock}"

    def approvisionner_produit(self, quantite, description, user):
        if quantite <= 0:
            raise ValueError("La quantité doit être positive.")

        self.stock += quantite
        self.save()

        #  Enregistrement dans l'historique des Approvisionnements
        Approvisionnement.objects.create(
            produit=self, quantite=quantite, description = description,
            created_by=user
        )


    def controle_stock_produit(self, quantite):
        if quantite <= 0:
            raise ValueError("La quantité doit être positive.")

        if quantite > self.stock:
            raise ValueError(f"{self.designation}, Stock insuffisant.")

    def update_stock(self, quantite):
        self.stock -= int(quantite)
        self.save()


class PrixProduit(MyBaseModel):
    prix_vente = models.BigIntegerField()
    produit = models.ForeignKey(Produit, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.produit.designation} - {self.prix_vente}"


class Vente(MyBaseModel):
    TYPE_DE_VENTE = [(1, "Cash"), (2, "Crédit")]
    reduction = models.IntegerField(null=True)
    type_vente = models.SmallIntegerField(choices=TYPE_DE_VENTE, default=1)
    montant_total = models.BigIntegerField(null=True)
    reference = models.CharField(max_length=20, unique=True, blank=True)
    client = models.ForeignKey(Client, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.reference


class ProduitVendu(MyBaseModel):
    vente = models.ForeignKey(Vente, on_delete=models.CASCADE, related_name="produits_vendus")
    produit = models.ForeignKey(Produit, on_delete=models.CASCADE)
    quantite = models.IntegerField()
    prix_vente_unitaire = models.BigIntegerField()

    def __str__(self):
        return f"{self.produit.designation} x {self.quantite} - {self.prix_vente_unitaire} GNF"

class Approvisionnement(MyBaseModel):
    produit = models.ForeignKey(Produit, on_delete=models.CASCADE)
    quantite = models.IntegerField()
    pau = models.BigIntegerField(null=True, blank=True)
    description = models.CharField(max_length=255, null=True, blank=True)


    def __str__(self):
        return f"{self.produit.designation} - {self.quantite}"


class Depense(MyBaseModel):
    ligne_depense = [("RESTAURANT", "RESTAURANT"), ("SALON", "SALON")]
    motif = models.TextField()
    montant = models.BigIntegerField()
    section = models.CharField(choices=ligne_depense, max_length=10)

    def __str__(self):
        return f"{self.montant} - {self.motif} - {self.section}"


class InitAbonnementService(MyBaseModel):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    montant_total = models.BigIntegerField()
    nb_seances = models.IntegerField()
    is_active = models.BooleanField(default=True)
    remise = models.BigIntegerField(null=True)


class DetailsAbonnementService(MyBaseModel):
    service = models.ForeignKey(Service, null=True, on_delete=models.SET_NULL, related_name="subscribed_service")
    prix_service = models.BigIntegerField()
    abonnement = models.ForeignKey(InitAbonnementService, on_delete=models.CASCADE)

class RepartitionMontantPrestation(MyBaseModel):
    init_prestation = models.ForeignKey(InitPrestation, on_delete=models.SET_NULL, null=True)
    employe = models.ForeignKey(Employe, on_delete=models.SET_NULL, null=True)
    montant_attribue = models.BigIntegerField()
    service = models.ForeignKey(Service, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.employe.first_name} {self.employe.last_name} - {self.montant_attribue}'

salon/forms.py
from django import forms
from .models import CategorieService, Service, Prestation, PrixService, Produit, Approvisionnement, InitPrestation, Depense


class CategorieForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].label = ''


    class Meta:
        model = CategorieService
        fields = ['nom_categorie']


class ServiceForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].label = ''


    class Meta:
        model = Service
        fields = ['designation', 'categorie']


class PrixServiceForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Supprimer les Labels par defaut
        for field_name in self.fields:
            self.fields[field_name].label = ''

    class Meta:
        model = PrixService
        fields = ['prix_service', 'service']


class InitPrestationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Supprimer les Labels par defaut
        for field_name in self.fields:
            self.fields[field_name].label = ''

    class Meta:
        model = InitPrestation
        fields = ['reference', 'montant_total', 'remise']

class PrestationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Supprimer les Labels par defaut
        for field_name in self.fields:
            self.fields[field_name].label = ''

    class Meta:
        model = Prestation
        fields = ['service', 'prix_service', 'init_prestation', 'quantite']


class ProduitForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].label = ''

    class Meta:
        model = Produit
        fields = ["designation", "prix_vente", "stock", "image"]


class ApproProduitForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].label = ''

    class Meta:
        model = Approvisionnement
        fields = ["produit", "quantite", "description"]


class DepensesForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].label = ''


    class Meta:
        model = Depense
        fields = ["motif", "montant", "section"]

salon/templates/salon/prix_services.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block page_title %} {{ page_title }} {% endblock %}
{% block main %}
<!-- Row starts -->
<div class="row gx-4">
  <div class="col-sm-12">
    <div class="card mb-4">
      <div class="card-header">
        <h5 class="card-title">Prix des Services</h5>
      </div>
      <div class="card-body">
        <div class="accordion" id="accordionSpecialTitle">
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingSpecialTitleOne">
              <button class="accordion-button" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapseSpecialTitleOne" aria-expanded="true"
                aria-controls="collapseSpecialTitleOne">
                <div class="d-flex flex-column">
                  <h5 class="m-0">Prix Services</h5>
                </div>
              </button>
            </h2>
            <div id="collapseSpecialTitleOne" class="accordion-collapse collapse show"
              aria-labelledby="headingSpecialTitleOne" data-bs-parent="#accordionSpecialTitle">
              <div class="accordion-body">
                <!-- Row starts -->
                <form method="POST" action="{% url 'add_prix_services' %}" class="row gx-4" id="prix-services-form">
                    {% csrf_token %}
                    <div class="col-xl-3 col-sm-4 col-12">
                        <div class="mb-3">
                            <label class="form-label" for="id_service">Selectionnez un Service</label>
                            {{ form.service | as_crispy_field }}
                        </div>
                    </div>
                    <div class="col-xl-3 col-sm-4 col-12">
                        <div class="mb-3">
                            <label class="form-label" for="id_prix_service">Entrez le Prix</label>
                            {{ form.prix_service | as_crispy_field }}
                        </div>
                    </div>

                    <!-- Zone d'affichage des messages -->
                    <div id="response-message" class="alert bg-success text-white alert-dismissible fade" role="alert">
                      <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert"
                        aria-label="Close"></button>
                    </div>

                    <div class="col-sm-12 col-12">
                        <button type="submit" class="btn btn-primary">Créer</button>
                    </div>
                </form>
                <!-- Row ends -->
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>
<!-- Row ends -->

<div class="card mb-4">
    <div class="card-header">
        <h5 class="card-title">Liste des Prix et Services</h5>
    </div>
    <div class="card-body">
        <div class="table-outer">
            <div class="table-responsive p-4">
                <table class="table align-middle table-hover m-0 truncate" id="table-prix-service">
                    <thead>
                    <tr>
                        <th>Services</th>
                        <th>Prix</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for prix in prix_services %}
                    <tr>
                        <td>
                            <p>{{ prix.service}} {{ employe.last_name }}</p>
                        </td>
                        <td>{{ prix.prix_service }}</td>
                        <td>
                            <a class="btn btn-danger btn-sm" href="#"><i class="bi bi-pencil"></i>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Custom JS files -->
{% block custom_js %}
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/datatables.min.js' %}"></script>
{% endblock %}
<script>
    $(document).ready(function(){
        // Gestion Prix Services
        $("#table-prix-service").DataTable({
          language: {
              processing: "Traitement en cours...",
              search: "Rechercher&nbsp;:&nbsp;",
              lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
              info:           "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
              infoEmpty:      "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
              loadingRecords: "Chargement en cours...",
              zeroRecords:    "Aucun &eacute;l&eacute;ment &agrave; afficher",
              emptyTable:     "Aucune donnée disponible dans le tableau",
              aria: {
                  sortAscending:  ": activer pour trier la colonne par ordre croissant",
                  sortDescending: ": activer pour trier la colonne par ordre décroissant"
              }
          }
        });

        function getCSRFToken(){
            const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]');
            return csrfToken ? csrfToken.value : "";
        }

        $("#prix-services-form").submit(function(e){
            e.preventDefault();

            const formData = {
                service: $("#id_service").val().trim(),
                prix: $("#id_prix_service").val().trim(),
            }

            if(!formData.service || !formData.prix){
                $("#response-message").text("Tous les champs sont obligatoires");
                $("#response-message").addClass('show');
                // Faire disparaître après 3 secondes (3000 ms)
                setTimeout(function () {
                     $("#response-message").removeClass('show').fadeOut();
                }, 3000);
            }

            $.ajax({
                url: $(this).attr('action'),
                method: 'POST',
                headers: { 'X-CSRFToken': getCSRFToken() },
                data: $(this).serialize(),
                success: function(res){
                    $("#response-message").text(res.msg);
                     $("#response-message").addClass('show');
                     // Reinitialiser le formulaire
                     $("#prix-services-form")[0].reset();
                     // Ajouter le nouvel Prix a la table
                      var newRow = `
                          <tr>
                              <td>${res.service}</td>
                              <td>${res.prix}</td>
                              <td>
                                <a class="btn btn-danger btn-sm" href="#"><i class="bi bi-pencil"></i>
                                </a>
                              </td>
                          </tr>
                      `
                      // Ajouter la nouvelle ligne a la table sans recharger la page
                      $("#table-prix-service tbody").prepend(newRow);
                      setTimeout(function () {
                         $("#response-message").removeClass('show').fadeOut();
                      }, 3000);
                },
                error: function(err){
                    $("#response-message").text(err.error);
                    $("#response-message").removeClass('bg-success');
                    $("#response-message").addClass('bg-danger').addClass('show');

                    setTimeout(function () {
                        $("#response-message").removeClass('show').fadeOut();
                    }, 3000);
                }
            }) // Fin Ajax
        })
    })
</script>
{% endblock %}