employe/urls.py
from django.urls import path

from employe import views

urlpatterns = [
    path("", views.employe, name="employe"),
    path("list/", views.get_employes, name="get_employes"),
    path("add/", views.add_employe, name="add_employe"),
    path("dashmin/filtre/", views.filtre_dashmin_data, name="filtre_dashmin_data"),
    path("dashmin/situation_salon/", views.entrees_sorties_salon, name="entrees_sorties_salon"),
    path("dashmin/situation_resto/", views.entrees_sorties_restaurant, name="entrees_sorties_resto"),
    path("performances/", views.performances, name="performances"),
    path("performances/performances_par_date/", views.performances_par_date, name="performances_par_date"),
    path("performances/details_prestation_par_id/<str:id_init_prest>/", views.details_prestation_par_id, name="details_prestation_par_id"),
    path("performances/attributions/", views.add_attributions, name="add_attributions"),
    path("performances/calcule_montant_par_employe/", views.montant_genere_par_employe, name="montant_genere_par_employe"),
]

marbika/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from employe.views import dashmin, login_user, logout_user

urlpatterns = [
    path("", dashmin, name="dashmin"),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
    path('admin/', admin.site.urls),
    path("employe/", include("employe.urls")),
    path("salon/", include("salon.urls")),
    path("restaurant/", include("restaurant.urls")),
    path("client/", include("client.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

salon/urls.py
from django.urls import path

from salon.views import *

urlpatterns = [
    path("services/", services, name="services"),
    path("services/add/", add_service, name="add_service"),
    path("services/get_services/", get_services, name="get_services"),
    path("services/get/", get_service, name="get_service"),
    path("services/update/", update_service, name="update_service"),
    path("services/montant_par_service/", montant_genere_par_service, name="montant_par_service"),
    path("categorie/add/", add_category, name="add_categorie"),
    path("categorie/get_categories/", get_categories, name="get_categories"),
    path("prix/", prix_services, name="prix_services"),
    path("prix/add/", add_prix_service, name="add_prix_services"),
    path("prestations/", prestations, name="prestations"),
    path("get_prestations/", get_prestations, name="get_prestations"),
    path("prestations_en_attentes/", prestations_en_attentes, name="prestations_en_attentes"),
    path("prestations/add/", add_prestation, name="add_prestations"),
    path("prestations/confirmer_prestation/", confirmer_prestation, name="confirmer_prestation"),
    path("prestations/details/<str:id_prestation>", get_prestation_details, name="get_prestation_details"),
    path("prestations/<str:service_id>/", get_prix_service, name="get_prix_service"),
    path("produits/", produits, name="produits"),
    path("produits/add/", add_produit, name="add_produit"),
    path("produits/list/", get_produits, name="get_produits"),
    path("produits/appro/", approvisionner_produit, name="approvisionner"),
    path("produits/shop/", shop_produits, name="shop"),
    path("produits/shop/details/<str:id_vente>/", details_vente, name="shop"),
    path("produits/vente/", vente_produits, name="vente_produits"),
    path("produits/list_clients/", get_clients, name="list_clients"),
    path("produits/liste_ventes/", get_ventes, name="liste_ventes"),
    path("depenses/", depenses, name="depenses"),
    path("depenses/add/", creer_depense, name="creer_depense"),
    path("depenses/list/", get_depenses, name="get_depenses"),
    path("depenses/calcul_depenses/", depense_semaine_mois_annee, name="calcul_depenses"),
]

employe/models.py
import uuid
from django.contrib.auth.models import AbstractUser
from django.db import models


class Employe(AbstractUser):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    telephone = models.CharField(max_length=18)

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.telephone})"



class MyBaseModel(models.Model):
    id = models.UUIDField(
        primary_key=True,
        editable=False,
        default=uuid.uuid4
    )
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(Employe, on_delete=models.SET_NULL, null=True,
                                   related_name="created_%(class)s_set")
    updated_at = models.DateTimeField(null=True, blank=True)
    updated_by = models.ForeignKey(Employe, null=True, blank=True,
                                   on_delete=models.SET_NULL, related_name="updated_%(class)s_set")


    class Meta:
        abstract = True

employe/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import Employe


class EmployeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields:
            self.fields[field_name].label = ''


    class Meta:
        model = Employe
        fields = ["first_name", "last_name", "email", "telephone"]


class EmployeCreationForm(UserCreationForm):
    class Meta:
        model = Employe
        fields = ("username", "first_name", "last_name", "email", "telephone")


class EmployeChangeForm(UserChangeForm):
    class Meta:
        model = Employe
        fields = ("username", "first_name", "last_name", "email", "telephone", "is_active", "is_staff")

employe/views.py
import http
import json
import uuid
from collections import defaultdict
from datetime import date, timedelta, datetime

import django.db.utils
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.crypto import get_random_string
from django.db import IntegrityError, transaction
from django.db.models import Sum, Q, Count, ExpressionWrapper, BigIntegerField, F
from django.db.models.functions import Extract, ExtractWeek
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.template.loader import render_to_string
from django.utils.html import escape
from django.views.decorators.http import require_http_methods

from client.models import Piscine
from employe.forms import EmployeForm
from employe.models import Employe
from restaurant.models import Commande
from salon.models import Vente, Depense, InitPrestation, Prestation, RepartitionMontantPrestation, Service

from salon.views import currency
from employe.common.utils import date_str_to_date_naive

tmp_base = "employe/"


def semaines():
    today = date.today()
    current_year = today.year

    # Commencer a partir du 1er Jan
    start_date = date(current_year, 1, 1)

    # Trouver le Lundi de la 1ere semaine
    start_date -= timedelta(days=start_date.weekday())

    list_semaines: list = []

    while start_date <= today:
        numero_semaine =  start_date.isocalendar().week
        annee_semaine = start_date.isocalendar().year
        mois_semaine = start_date.strftime("%B")
        num_mois_semaine = start_date.month

        list_semaines.append({
            "numero_semaine": numero_semaine,
            "annee_semaine": annee_semaine,
            "mois_semaine": mois_semaine,
            "num_mois_semaine": num_mois_semaine,
        })

        start_date += timedelta(weeks=1)

    list_semaines = sorted(list_semaines, key=lambda k: k['numero_semaine'], reverse=True)
    return list_semaines


def groupe_prestations_par_reference(year: int):
    init_prestations = InitPrestation.objects.prefetch_related(
        'prestation_set__fait_par',
        'prestation_set__service',
    ).order_by('-created_at')

    prestation_par_prestataire: list = []

    for init_pres in init_prestations:
        employe_data = defaultdict(lambda : {
            "initiales": "",
            "nom": "",
            "prenom": "",
            "email": "",
            "nb_services": 0,
            "services": list(),
        })

        for prestation in init_pres.prestation_set.all():
            prestataire = prestation.fait_par.all()
            service = prestation.service

            if prestataire and service:
                key = prestataire.id
                employe_data[key]["nom"] = prestataire.last_name
                employe_data[key]["prenom"] = prestataire.first_name
                employe_data[key]["email"] = prestataire.email
                employe_data[key]["nb_services"] += 1
                employe_data[key]["services"].append(service.designation)

        prestation_par_prestataire.append({
            "reference": init_pres.reference,
            "montant_total": currency(init_pres.montant_total),
            "remise": currency(init_pres.remise),
            "net_paye": currency(init_pres.montant_total - init_pres.remise),
            "date": init_pres.created_at.strftime("%d/%m/%Y"),
            "prestataire": [
                {
                    "initiales": data["prenom"][0] + "" + data["nom"][0],
                    "nom_complet": data["prenom"] + " " + data["nom"],
                    "email": data["email"],
                    "nb_services": data["nb_services"],
                    "services": ", ".join(data["services"]),
                } for data in employe_data.values()
            ]
        })

    return prestation_par_prestataire


@login_required(login_url="login")
def dashmin(request):
    current_year = date.today().year

    # prestations_par_reference = groupe_prestations_par_reference(year=current_year)
    context = {
        "semaines": semaines(),
        "page_title": "Analytics",
        "prestations_par_reference": [],
    }
    return render(request, "dashboard.html", context)


@login_required(login_url="login")
def employe(request):
    form = EmployeForm()

    context = {
        "form": form,
        "page_title": "Employés",
    }
    return render(request, tmp_base + "add_employe.html", context)


@require_http_methods(["GET"])
def get_employes(request):
    employes = Employe.objects.all()
    list_employes: list = []
    for employe in employes:
        list_employes.append({
            "id": employe.id,
            "full_name": employe.first_name + " " + employe.last_name,
            "telephone": employe.telephone,
            "email": employe.email,
            "action": f'<a class="btn btn-danger btn-sm" href="#"><i class="bi bi-pencil"></i></a>'
        })

    return JsonResponse({"success": True, "data": list_employes})


@login_required(login_url="login")
def add_employe(request):
    if request.method == "POST":

        try:
            data = json.loads(request.body)
            #  Verification des champs cote serveur
            required_fields = ['first_name', 'last_name', 'telephone']
            for field in required_fields:
                if not escape(data.get(field)):
                    return JsonResponse({"error": f"{field} est obligatoire"}, status=400)

            # Enregistrement de l'employe
            # Recuperer le prenom de l'employe et le mettre tout en minuscule sans espace
            base_first_name = data['first_name'].lower().replace(" ", "")

            # Ajouter 8 caracteres uniques d'un uuid au prenom pour former le username par default
            unique_part = str(uuid.uuid4())[:8]
            username = f"{base_first_name}_{unique_part}"
            password = get_random_string(10)
            employee = Employe.objects.create_user(
                first_name=data['first_name'], last_name=data['last_name'], password=password,
                email=data['email'], telephone=data['telephone'], username=username,
            )


            return JsonResponse({ "msg": "Employé enregistré avec succès.",
                                  "first_name": employee.first_name,
                                  "last_name": employee.last_name,
                                  "telephone": employee.telephone,
                                  "email": employee.email})
        except json.JSONDecodeError:
            return JsonResponse({"error": "Données invalides."}, status=400)
        except IntegrityError as e:
            if 'employe_employe_email_key' in str(e):
                return JsonResponse({"error": "Ce email existe déjà."}, status=409)
            return JsonResponse({"error": "Echec de l'enregistrement pour des raison de doublon"}, status=409)


def get_stats_vente_produits(date_debut_str, date_fin_str):
    try:
        ventes = Vente.objects.filter(
            created_at__gte=date_debut_str,
            created_at__lte=date_fin_str,
        )

        # Nombre de Ventes réalisé
        nb_ventes = ventes.count()
        sum_montant_ventes = ventes.aggregate(Sum("montant_total"))['montant_total__sum'] or 0
        sum_remise_ventes = ventes.aggregate(Sum("reduction"))['reduction__sum'] or 0

        total_net_ventes = sum_montant_ventes - sum_remise_ventes

        # Nombre de Ventes en Cash
        nb_ventes_cash = ventes.filter(type_vente=1).count()

        # Montant total de Ventes en Cash
        resultats_ventes_cash = ventes.aggregate(
            sum_vente_cash=Sum("montant_total", filter=Q(type_vente=1)),
            sum_remise_vente_cash=Sum("reduction", filter=Q(type_vente=1)),
        )
        sum_ventes_cash = resultats_ventes_cash['sum_vente_cash'] or 0
        sum_remise_ventes_cash = resultats_ventes_cash['sum_remise_vente_cash'] or 0

        total_ventes_cash = sum_ventes_cash - sum_remise_ventes_cash


        # Nombre de Ventes à Crédit
        nb_ventes_credits = ventes.filter(type_vente=2).count()

        # Montant total de Ventes à Crédit
        resultats_ventes_credits = ventes.aggregate(
            total_montant_credit=Sum("montant_total", filter=Q(type_vente=2)),
            total_remise_credit=Sum("reduction", filter=Q(type_vente=2))
        )
        sum_ventes_credit = resultats_ventes_credits["total_montant_credit"] or 0
        sum_remise_ventes_credit = resultats_ventes_credits["total_remise_credit"] or 0

        total_ventes_credits = sum_ventes_credit - sum_remise_ventes_credit

        response = {
            "nb_ventes": nb_ventes,
            "sum_montant_ventes": sum_montant_ventes,
            "sum_remise_ventes": sum_remise_ventes,
            "total_net_ventes": total_net_ventes,
            "nb_ventes_cash": nb_ventes_cash,
            "sum_ventes_cash": sum_ventes_cash,
            "sum_remise_ventes_cash": sum_remise_ventes_cash,
            "total_ventes_cash": total_ventes_cash,
            "nb_ventes_credits": nb_ventes_credits,
            "sum_ventes_credit": sum_ventes_credit,
            "sum_remise_ventes_credit": sum_remise_ventes_credit,
            "total_ventes_credits": total_ventes_credits,
        }
        return response
    except Vente.DoesNotExist:
        return None


def get_service_le_plus_demande(filtre):
    # le parametre 'filtre' est de type dictionnaire au format:
    # {"created_at__date__week": week_num}
    return (
        Prestation.objects.filter(**filtre)
        .values("service__id", "service__designation")
        .annotate(nb_services=Count("id"))
        .order_by("-nb_services")
        .first()
    )

def get_montant_total_par_service(id_service, filtres):
    return (
        Prestation.objects.filter(service__id=id_service, **filtres)
        .aggregate(total_montant=Sum("prix_service"))["total_montant"] or 0
    )

employe/templates/employe/add_employe.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block page_title %} {{ page_title }} {% endblock %}
{% block main %}
<!-- Row starts -->
<div class="row gx-4">
    <div class="col-sm-12">
        <div class="card mb-4">
            <div class="card-header">
                <h5 class="card-title">Création d'un nouveau Employé</h5>
            </div>
            <div class="card-body">
                <div class="accordion" id="accordionSpecialTitle">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingSpecialTitleTwo">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                    data-bs-target="#collapseSpecialTitleTwo" aria-expanded="false"
                                    aria-controls="collapseSpecialTitleTwo">
                                <div class="d-flex flex-column">
                                    <h5 class="m-0">Nouveau Employé</h5>
                                </div>
                            </button>
                        </h2>
                        <div id="collapseSpecialTitleTwo" class="accordion-collapse collapse"
                             aria-labelledby="headingSpecialTitleTwo" data-bs-parent="#accordionSpecialTitle">
                            <div class="accordion-body">

                                <!-- Row starts -->
                                <form method="POST" action="{% url 'add_employe' %}" class="row gx-4" id="employe-form">
                                    {% csrf_token %}
                                    <div class="col-xl-3 col-sm-4 col-12">
                                        <div class="mb-3">
                                            <label class="form-label" for="id_first_name">Prénom</label>
                                            {{ form.first_name | as_crispy_field }}
                                        </div>
                                    </div>
                                    <div class="col-xl-3 col-sm-4 col-12">
                                        <div class="mb-3">
                                            <label class="form-label" for="id_last_name">Nom</label>
                                            {{ form.last_name | as_crispy_field }}
                                        </div>
                                    </div>
                                    <div class="col-xl-3 col-sm-4 col-12">
                                        <div class="mb-3">
                                            <label class="form-label" for="id_email">Email</label>
                                            {{ form.email | as_crispy_field }}
                                        </div>
                                    </div>
                                    <div class="col-xl-3 col-sm-4 col-12">
                                        <div class="mb-3">
                                            <label class="form-label" for="id_telephone">Téléphone</label>
                                            {{ form.telephone | as_crispy_field }}
                                        </div>
                                    </div>

                                    <!-- Zone d'affichage des messages -->
                                    <div id="response-message" class="alert bg-success text-white alert-dismissible fade" role="alert">

                                      <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                                    </div>

                                    <div class="col-sm-12 col-12">
                                        <div class="d-flex gap-2 justify-content-end">
                                            <!--                      <button type="button" class="btn btn-secondary">Clear</button>-->
                                            <button type="submit" class="btn btn-primary">Créer</button>
                                        </div>
                                    </div>
                                </form>
                                <!-- Row ends -->

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mb-4">
            <div class="card-header">
                <h5 class="card-title">Liste des Employés</h5>
            </div>
            <div class="card-body">
                <div class="table-outer">
                    <div class="table-responsive">
                        <table class="table align-middle table-hover m-0 truncate" id="table-employe">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Employee</th>
                                <th class="text-center">Téléphone</th>
                                <th>Email</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            <!-- Contenu chargé par Ajax-->

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Custom JS files -->
{% block custom_js %}
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/datatables.min.js' %}"></script>
{% endblock %}
<script>
    $(document).ready(function(){

        var tableEmploye = $("#table-employe").DataTable({
            ajax: '/employe/list/',
            columns: [
                {
                    data: null,
                    render: function(data, type, row, meta){
                        return meta.row + 1;
                      }
                },
                { data: 'full_name' },
                { data: 'telephone' },
                { data: 'email' },
                { data: 'action' },
            ],
            language: {
                processing: "Traitement en cours...",
                search: "Rechercher&nbsp;:&nbsp;",
                lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
                info:           "Affichage de l'&eacute;lement _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                infoEmpty:      "Affichage de l'&eacute;lement 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
                loadingRecords: "Chargement en cours...",
                zeroRecords:    "Aucun &eacute;l&eacute;ment &agrave; afficher",
                emptyTable:     "Aucune donnée disponible dans le tableau",
                aria: {
                    sortAscending:  ": activer pour trier la colonne par ordre croissant",
                    sortDescending: ": activer pour trier la colonne par ordre décroissant"
                }
            }
        });

        function getCSRFToken(){
            const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]');
            return csrfToken ? csrfToken.value : "";
        }

        $("#employe-form").submit(function(event){
            event.preventDefault();

            const actionUrl = $(this).attr('action');

            // Collecte des données du formulaire
            const formData = {
                first_name: $('#id_first_name').val().trim(),
                last_name: $('#id_last_name').val().trim(),
                telephone: $('#id_telephone').val().trim(),
                email: $('#id_email').val().trim(),
            };

            if(!formData.first_name || !formData.last_name || !formData.telephone){
                $("#response-message").text("Tous les champs sont obligatoires.")
                $('#response-message').removeClass("bg-success").addClass('show bg-warning').fadeIn();
                setTimeout(function(){
                    $("#response-message").removeClass('bg-warning show').fadeOut();
                }, 5000)
                return
            }

            // Envoi de la requête AJAX
            $.ajax({
                url: actionUrl,
                method: 'POST',
                headers: { 'X-CSRFToken': getCSRFToken() },
                data: JSON.stringify(formData),
                contentType: 'application/json',
                dataType: 'json',
                success: function(res){
                    $('#response-message').text(res.msg);
                    $('#response-message').addClass('show').fadeIn();

                    // Ajouter le nouvel Employe a la table
                    var newRow = `
                        <tr>
                            <td>${res.first_name} ${res.last_name}</td>
                            <td>${res.telephone}</td>
                            <td>${res.email}</td>
                        </tr>
                    `
                    // Recharger les nouvelles data dans la table
                    //$("#table-emplye tbody").prepend(newRow);
                    tableEmploye.ajax.reload();

                    // Faire disparaître après 3 secondes (3000 ms)
                    setTimeout(function () {
                        $('#response-message').removeClass('show').fadeOut();
                    }, 3000);

                    $('#employe-form')[0].reset();

                    $("#table-emplye tbody").append(res.new_row_html)
                },
                error: function(xhr){
                    const errorResponse = xhr.responseJSON ? xhr.responseJSON.error : 'Erreur serveur.';
                    $('#response-message').text(`Erreur: ${errorResponse}`);
                    $('#response-message').removeClass('bg-success')
                    $('#response-message').addClass('bg-warning show').fadeIn();
                    // Faire disparaître après 3 secondes (3000 ms)
                    setTimeout(function () {
                        $('#response-message').removeClass('show').fadeOut();
                        $('#response-message').removeClass('bg-warning');
                    }, 3000);
                },
            })

        })
    })
</script>
<!-- Row ends -->
{% endblock %}

employe/templates/employe/login.html
<!DOCTYPE html>
<html lang="fr">
{% load static %}
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Complexe Marbika</title>

    <!-- Meta -->
    <meta property="og:title" content="Complexe Marbika">
    <meta property="og:type" content="Website">
    <meta property="og:site_name" content="Marbika">
<!--    <link rel="shortcut icon" href="assets/images/favicon.svg" />-->

    <!-- *************
			************ CSS Files *************
		************* -->
    <link rel="stylesheet" href="{% static 'assets/fonts/bootstrap/bootstrap-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/main.min.css' %}" />

  </head>

  <body>
    {% if messages %}
        {% for msg in messages %}
        <div class="alert alert-warning w-50 m-auto alert-dismissible fade " id="alert" role="alert">
            {{ msg }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}

      {% endif %}
    <!-- Auth wrapper starts -->
    <div class="auth-wrapper">

      <!-- Form starts -->
      <form id="loginForm" action="{% url 'login' %}" method="POST">

        {% csrf_token %}

        <!-- Authbox starts -->
        <div class="auth-box">

          <!-- Logo starts -->
            <div id="logo" class="d-flex justify-content-center">
                <a href="{% url 'login' %}" class="auth-logo mb-4">
                    <img src="{% static 'assets/images/LogoMarbika.png' %}" alt="Logo Marbika" />
                </a>
            </div>

          <!-- Logo ends -->

          <h4 class="mb-4 text-center">Connexion</h4>

            {% if next %}
                <input type="hidden" name="next" value="{{ next }}">
            {% endif %}

          <div class="mb-2">
            <label class="form-label" for="username">Nom d'utilisateur <span class="text-danger">*</span></label>
            <input type="text" id="username" name="username" class="form-control" placeholder="Entrez votre nom d'utilisateur" />
          </div>

          <div class="mb-2">
            <label class="form-label" for="password">Mot de passe <span class="text-danger">*</span></label>
            <div class="input-group">
              <input type="password" id="password" name="password" autocomplete="false" class="form-control" placeholder="Entrez votre mot de passe" />
              <button class="btn btn-outline-secondary" id="showPassword" type="button">
                <i class="bi bi-eye"></i>
              </button>
            </div>
          </div>


          <div class="d-grid gap-2">
            <button type="submit" class="btn btn-danger">Se Connecter</button>
          </div>

        </div>
        <!-- Authbox ends -->

      </form>
      <!-- Form ends -->

    </div>
    <!-- Auth wrapper ends -->

    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>

    <script>
       $(document).ready(function(){
            $("#showPassword").on('click', function(){
                $("#password").attr("type") == "password" ?
                $("#password").attr("type", "text") :
                $("#password").attr("type", "password");
            })
       })
    </script>
    <script>
        var alertMsg = document.getElementById("alert")
        {% if messages %}
          alertMsg.classList.add("show")
          setTimeout(()=>{
            alertMsg.classList.remove("show")
          }, 3000)
        {% endif %}

    </script>


  </body>

</html>